/* tac.js — GENERATED by scripts/build-try-a-class.mjs. Do not hand-edit.
   Fills the dates and the answer line on /try-a-class from data/site-config.js.
   Rebuild after any date change, then run DEPLOY-classes.shoonyadance.com.command. */
(function () {
  'use strict';
  var D = {"openDoors":["2026-09-13","2027-01-31","2027-06-13"],"trialWeeks":[{"start":"2026-09-14","end":"2026-09-19"},{"start":"2027-02-15","end":"2027-02-20"}],"eventUrls":{"2026-09-13":"https://www.shoonyadance.com/calendar/opendeurdag-gratis-dansen-gent-13-september","2026-09-14":"https://www.shoonyadance.com/calendar/free-trial-week-14-19-september"},"schedule":"https://schedule.shoonyadance.com/schedule-sep-2026/","partners":["Argentine Tango","Bachata","Cuban Salsa","Kizomba","Rueda de Casino"],"styles":25};
  if (!document.getElementById('tac')) return;

  var d = function (s) { return new Date(s + 'T00:00:00'); };
  var now = new Date(); now.setHours(0, 0, 0, 0);
  var day = 864e5;
  var M = ['January','February','March','April','May','June','July','August','September','October','November','December'];

  function one(a) { return a.getDate() + ' ' + M[a.getMonth()] + ' ' + a.getFullYear(); }
  function span(a, b) {
    if (a.getMonth() === b.getMonth()) return a.getDate() + '\u2013' + b.getDate() + ' ' + M[a.getMonth()] + ' ' + a.getFullYear();
    return a.getDate() + ' ' + M[a.getMonth()] + ' \u2013 ' + b.getDate() + ' ' + M[b.getMonth()] + ' ' + b.getFullYear();
  }
  function iso(dt) {
    return dt.getFullYear() + '-' + ('0' + (dt.getMonth() + 1)).slice(-2) + '-' + ('0' + dt.getDate()).slice(-2);
  }
  function ev(dt) { return D.eventUrls[iso(dt)] || null; }
  function set(id, html) { var e = document.getElementById(id); if (e) e.innerHTML = html; }

  // Only dates still ahead. A past date left in the config must not resurface here —
  // that is exactly how a June date was still being shown in August.
  var doors = D.openDoors.map(d).filter(function (x) { return x >= now; });
  var weeks = D.trialWeeks.map(function (w) { return { s: d(w.start), e: d(w.end) }; })
                          .filter(function (w) { return w.e >= now; });

  // The spaces around the separator are LOAD-BEARING: they are the only line-break
  // opportunities in the list. Without them nowrap dates make one unbreakable string that
  // forces the grid wider than a phone viewport and the page scrolls sideways.
  // Each date is one unbreakable unit: a three-date line must wrap BETWEEN dates, never
  // inside one ("13 September / 2026"). CSS alone cannot do this on a plain text node.
  function list(parts, empty) {
    if (!parts.length) return '<span class="tac-d-none">' + empty + '</span>';
    // The separator belongs to the date that FOLLOWS it, so a wrapped line never ends on a
    // dangling middle dot.
    return parts.map(function (t, i) {
      return '<span class="tac-d">' + (i ? '<span class="tac-sep">\u00b7</span> ' : '') + t + '</span>';
    }).join(' ');
  }
  set('tac-od-dates', list(doors.map(one), 'Dates for next season are announced in spring.'));
  set('tac-tw-dates', list(weeks.map(function (w) { return span(w.s, w.e); }), 'Announced with each new semester.'));

  var today  = doors.filter(function (x) { return +x === +now; })[0] || null;
  var next   = doors.filter(function (x) { return x > now; })[0] || null;
  var inWeek = weeks.filter(function (w) { return now >= w.s && now <= w.e; })[0] || null;
  var upcoming = weeks.filter(function (w) { return w.s > now; })[0] || null;
  // Registration stays open the first three weeks of a semester; each semester opens with
  // its trial week (semester.start === trialWeek.start in config).
  var justRan = D.trialWeeks.map(function (w) { return { s: d(w.start), e: d(w.end) }; })
    .filter(function (w) { return now > w.e && now <= new Date(+w.s + 21 * day); })[0] || null;

  // Same priority order as the homepage banner: lead with the NEAREST opportunity.
  var line, href = D.schedule, label = 'See the schedule';
  if (today) {
    line = '<b>Yes \u2014 today.</b> Open Door Day is running right now. Free, no booking, no Shoonya ID. Walk in, pick a class, join it.';
    if (ev(today)) { href = ev(today); label = "See today's programme"; }
  } else if (inWeek) {
    line = '<b>Yes \u2014 all week.</b> Until <b>' + one(inWeek.e) + '</b> every weekly class is free to try. No registration needed \u2014 pick a class from the timetable and arrive 10 minutes early.';
  } else if (justRan) {
    line = '<b>Yes.</b> The free week is over, but registration stays open for the <b>first three weeks</b> of the semester. Pick your class and start this week.'
         + (next ? ' The next Open Door Day is ' + one(next) + '.' : '');
  } else if (next && (!upcoming || next <= upcoming.s)) {
    line = '<b>Yes.</b> The next Open Door Day is <b>' + one(next) + '</b> \u2014 free, no booking, just walk in.'
         + (upcoming ? ' And from <b>' + span(upcoming.s, upcoming.e) + '</b> every weekly class is free to try.' : '');
    if (ev(next)) { href = ev(next); label = 'See the Open Door programme'; }
  } else if (upcoming) {
    line = '<b>Yes.</b> From <b>' + span(upcoming.s, upcoming.e) + '</b> every weekly class is free to try \u2014 no registration needed.'
         + (next ? ' The next Open Door Day is ' + one(next) + '.' : '');
    if (ev(upcoming.s)) { href = ev(upcoming.s); label = 'How the trial week works'; }
  } else {
    // No free dates configured. Never claim one — say the thing that is still true.
    line = '<b>Yes \u2014 ask us.</b> Between our free open days you can still arrange to sit in on a class. Next season\u2019s free dates are announced in spring.';
  }
  // Partner list, generated. Reads "A, B, C, D and E" — never a trailing comma, never a
  // stale hand-typed name.
  var pl = D.partners;
  if (pl.length) {
    var names = pl.length === 1 ? pl[0]
      : pl.slice(0, -1).join(', ') + ' and ' + pl[pl.length - 1];
    set('tac-partner-line', 'For <b>' + names + '</b> we recommend bringing a partner.');
    set('tac-partner-count', pl.length === 1 ? 'One style' : pl.length + ' styles');
  }

  // Style count + the timetable link on the closing band.
  if (D.styles) set('tac-style-count', String(D.styles));
  var sch = document.getElementById('tac-timetable');
  if (sch) sch.href = D.schedule;

  set('tac-answer-line', line);
  var cta = document.getElementById('tac-answer-cta');
  if (cta) { cta.href = href; cta.textContent = label; }
})();
