/* trial-banner.js — GENERATED by scripts/build-trial-banner.mjs. Do not hand-edit.
   Dates from data/site-config.js. Expires itself. Rebuild after any date change, then
   run DEPLOY-classes.shoonyadance.com.command. */
(function () {
  'use strict';
  var D = {"openDoors":["2026-09-13","2027-01-31","2027-06-13"],"trialWeeks":[{"start":"2026-09-14","end":"2026-09-19"},{"start":"2027-02-15","end":"2027-02-20"}]};
  var el = document.getElementById('shoonya-trial');
  if (!el) return;

  var d = function (s) { return new Date(s + 'T00:00:00'); };
  var now = new Date(); now.setHours(0, 0, 0, 0);
  var day = 864e5;

  var doors = D.openDoors.map(d);
  var weeks = D.trialWeeks.map(function (w) { return { s: d(w.start), e: d(w.end) }; });

  var today    = doors.filter(function (x) { return +x === +now; })[0] || null;
  var next     = doors.filter(function (x) { return x > now; })[0] || null;
  var inWeek   = weeks.filter(function (w) { return now >= w.s && now <= w.e; })[0] || null;
  var upcoming = weeks.filter(function (w) { return w.s > now; })[0] || null;
  // Registration stays open the first three weeks of a semester; each semester begins with
  // its trial week (true for semester 1 in config, where semester.start === trialWeek.start).
  var justRan  = weeks.filter(function (w) { return now > w.e && now <= new Date(+w.s + 21 * day); })[0] || null;

  var M = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  function fmt(a, b) {
    if (!b) return a.getDate() + ' ' + M[a.getMonth()] + ' ' + a.getFullYear();
    if (a.getMonth() === b.getMonth()) return a.getDate() + '–' + b.getDate() + ' ' + M[a.getMonth()] + ' ' + a.getFullYear();
    return a.getDate() + ' ' + M[a.getMonth()] + ' – ' + b.getDate() + ' ' + M[b.getMonth()] + ' ' + b.getFullYear();
  }
  // a trial week counts as "following" a door if it starts within 45 days of it
  function weekAfter(door) {
    return weeks.filter(function (w) { return w.s >= door && w.s - door < 45 * day; })[0] || null;
  }

  // PRIORITY: always lead with the NEAREST opportunity.
  //   1 door today · 2 trial week running · 3 registration window still open
  //   4 whichever of {next door, next trial week} comes first · 5 nothing
  // Getting this order wrong showed a door four months out while a trial week was five
  // days away, and buried the live registration window behind a distant invite.
  var head, body, sub = '';
  if (today) {
    var wT = weekAfter(today);
    head = 'Open Door Day is <em>today</em>.';
    body = 'Free, no booking — just walk in.' + (wT ? ' And from <strong>' + fmt(wT.s, wT.e) + '</strong> every weekly class is free to try.' : '');
    sub  = 'Check the schedule, pick a class, and arrive 10 minutes early.';
  } else if (inWeek) {
    head = 'Missed the Open Door Day? Every class is still free this week.';
    body = 'Until <strong>' + fmt(inWeek.e) + '</strong>, every weekly class is free to try. No registration needed.';
    sub  = 'Pick your class from the schedule and arrive 10 minutes early. After that, you can still register during the first three weeks.';
  } else if (justRan) {
    head = 'You can still join this semester.';
    body = 'Registration stays open for the <strong>first three weeks</strong>. Pick your class and start this week.';
    sub  = next ? 'Next Open Door Day: ' + fmt(next) + '.' : '';
  } else if (next || upcoming) {
    // lead with whichever is sooner
    var doorFirst = next && (!upcoming || next <= upcoming.s);
    if (doorFirst) {
      var wN = weekAfter(next);
      head = 'Try any class for free.';
      body = 'Open Door Day is <strong>' + fmt(next) + '</strong> — free, no booking, just walk in.' +
             (wN ? ' Then from <strong>' + fmt(wN.s, wN.e) + '</strong> every weekly class is free to try.' : '');
      sub  = 'Check the schedule, pick your class, and arrive 10 minutes early.';
    } else {
      head = 'Try any class for free.';
      body = 'Every weekly class is free to try from <strong>' + fmt(upcoming.s, upcoming.e) + '</strong>. No registration needed.';
      sub  = (next ? 'Next Open Door Day: ' + fmt(next) + '. ' : '') + 'Check the schedule and arrive 10 minutes early.';
    }
  } else {
    return; // nothing truthful left to say
  }

  var s = document.createElement('style');
// max-width keeps the measure readable: on the homepage the section is 1200px+ wide, which
  // ran the body text to ~158 characters a line (comfortable is 65-75). Centred so it sits
  // with the page's centred sections instead of stranded against the left edge.
  s.textContent = '#shoonya-trial .st{border:1px solid #E0CCF8;background:#F7F1FF;border-radius:10px;padding:1.35rem 1.6rem;margin:1.5rem auto;max-width:40rem;font-family:inherit}' +
    '#shoonya-trial .st-h{font-size:1.05rem;font-weight:700;color:#4A2A75;margin:0 0 .5rem;line-height:1.3}' +
    '#shoonya-trial .st-h em{font-style:normal;color:#B564F7}' +
    '#shoonya-trial .st-b{font-size:.95rem;color:#333;line-height:1.6;margin:0}' +
    '#shoonya-trial .st-s{display:block;margin-top:.5rem;font-size:.87rem;color:#5a5a5a}' +
    '#shoonya-trial .st-c{display:inline-block;margin-top:1rem;background:#B564F7;color:#fff!important;font-size:.8rem;font-weight:700;letter-spacing:.06em;text-transform:uppercase;padding:.7rem 1.4rem;border-radius:8px;text-decoration:none!important}' +
    '@media(max-width:600px){#shoonya-trial .st{padding:1.1rem 1.15rem}}';
  document.head.appendChild(s);

  el.innerHTML = '<div class="st"><p class="st-h">' + head + '</p><p class="st-b">' + body +
    (sub ? '<span class="st-s">' + sub + '</span>' : '') + '</p>' +
    '<a class="st-c" href="https://schedule.shoonyadance.com/schedule-sep-2026/">See the schedule →</a></div>';
})();
